### ISSUE TITLE
what is the purpose of the notifications table? it isn't used?

### ISSUE THREAD

**Issue by vesper8** [pimhooghiemstra/plint-pwa-api#1]
I noticed in your migrations that you create a notifications table with a read_at field, but nowhere in your code is this table referenced nor the field read_at.. was this something you were planning on adding and decided not to?

**Comment by vesper8** [comment]
nevermind.. I see this is part of core laravel now. I don't really understand how the read_at works though.. I guess this isn't implemented in this demo?

**Comment by pimhooghiemstra** [comment]
Well, it could be used in an improved version. You could for example, show the user he/she has X notifications. Once all notifications are read, or a button 'clear all' is clicked, the notifications in the db should be updated. I would use the read_at column for this.

But you are right, this is not included in the demo.
